### PR TITLE
Use modern fluentd plugin manner

### PR DESCRIPTION
**Pull request by cosmo0920**
* Use `log` instead of `$log`
* Use `router#emit` instead of `Engine#emit` (In v0.14, this code will be treated as a bug)
* Reorganize .travis.yml

### CODE REVIEW

**Comment by cosmo0920** [comment]
@y-ken ping?
`Engine.emit` is already treated as a bug in Fluentd v0.14 and it will be included in td-agent3.

**Comment by y-ken** [comment]
Thank you.
Would you please update the README with following updates?
 * update to td-agent2 era style. for example, `@type` and installation steps
* for td-agent2, update installation command with version

**Comment by y-ken** [comment]
Is it full compatible with td-agent1 and td-agent2?

**Comment by cosmo0920** [comment]
Yes, https://github.com/y-ken/fluent-plugin-munin/pull/3/files#diff-36a9cd9540e62bc2fafa68f49191d002R7 ensures to make compatible against them.

**Comment by cosmo0920** [comment]
But `@type` style config syntax is not supported in v0.10. :(

**Comment by cosmo0920** [comment]
> update to td-agent2 era style. for example, @type and installation steps
> for td-agent2, update installation command with version

I've added `td-agent2` style installation command, but I left as-is example configure.
Because `@type` syntax is not supported in v0.10.
If we use `@type` syntax in example config and README, we should drop v0.10 support.

**Comment by cosmo0920** [comment]
Any progress?

**Review by y-ken — APPROVED** [review]
@cosmo0920 sorry for late response. LGTM! 👍

**Pull request merged**
